name: Azure Functions API CI/CD

on:
  workflow_run:
    workflows: [Deploy Bicep file]
    types:
      - completed

env:
  AZURE_FUNCTIONAPP_NAME: 'func-http-trigger-resume'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './api'       # set this to the path to your function app project, defaults to the repository root
  AZURE_STATIC_WEB_APP_NAME: 'web-resume-00'   # set this to the name of your static web app on Azure
  AZURE_STATIC_WEB_APP_PACKAGE_PATH: './webpage'       # set this to the path to your static web app project, defaults to the repository root
  PYTHON_VERSION: '3.11'                     # set this to the python version to use (e.g. '3.6', '3.7', '3.8')

jobs:
  build_and_deploy_function:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Install Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true

    # not a perfect solution to always chose latest rg, but this is single deployment with hardcoded rg name
    # - name: 'Get the last resource group name' 
    #   id: rg
    #   run: |
    #     rgname=$(az group list -o yaml | grep -o '\sresume.*' | tail -1)

    #     echo "::set-output name=rgname::$rgname"

    # - name: 'Deploy website content to Static Web Apps'
    #   run: |
    #     az staticwebapp deploy \
    #     --source "${{ env.AZURE_STATIC_WEB_APP_PACKAGE_PATH }}" \
    #     --name "${{ env.AZURE_STATIC_WEB_APP_NAME }}" \
    #     --resource-group "${{ steps.rg.outputs.rgname }}"