name: Deploy Bicep file
on:
  #workflow_call:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  login-and-deploy-bicep:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: | 
          az account show

    - name: Deploy Bicep file
      uses: azure/cli@v1
      with:
        inlineScript: |
          az deployment sub create \
            --name deploy-${{ github.run_id }} \
            --template-file bicep/resumeChallenge.bicep \
            -p resourceGroupName=rg-resume-00 resourceGroupLocation=northeurope \
            -l northeurope