name: Deploy Bicep file
on:
  workflow_call:
  # push:
  #   branches:
  #     - main
  
jobs:
  login-and-deploy-bicep:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep file
      uses: azure/cli@v1
      with:
        inlineScript: |
          az deployment sub create \
            --name deploy-${{ github.run_id }} \
            --template-file bicep/resume_challenge.bicep \
            -p resourceGroupName=rg-resume-00 resourceGroupLocation=northeurope \
            -l northeurope