name: Deploy Bicep file
on:
  #workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github'
      - 'api/**'
      - 'bicep/**'
      - 'tests/**'
      - 'webpage/**'

  # Mind that resource group, static web app, and function app names are static in this deployment
  # and they are hardcoded in the workflow files to shorter the code because
  # reusable workflows are unrealiable - workflow_call is skipping jobs in this case and the bug is already 1 year old
  # Adding values to repository secrets can be a cleaner version of static values
  ###
  # Resource group location can be selected, but in case of StaticWebApp is hard set in staticWebApp.bicep as pool of options is limited
  # Problem with asset location can also happen when creating another Azure resources and that will fail the deployment
env:
  RESOURCE_GROUP_NAME: 'resume-live-01'   # set this to the name of your resource group on Azure
  RESOURCE_GROUP_LOCATION: 'northeurope'   # set this to the location of your resource group on Azure

jobs:
  login-and-deploy-bicep:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: | 
          az account show


    - name: Deploy Bicep file
      uses: azure/cli@v1
      with:
        inlineScript: |
          az deployment sub create \
            --name deploy-${{ github.run_id }} \
            --template-file bicep/resumeChallenge.bicep \
            -p resourceGroupName=${{env.RESOURCE_GROUP_NAME}} resourceGroupLocation=${{env.RESOURCE_GROUP_LOCATION}} \
            -l northeurope