name: Deploy Resume Challenge to Azure
on: 
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
        YOLO:
            default: true
            type: boolean
jobs:
    deploy-az-resources:
        uses: ./.github/workflows/bicep_deployment.yml
        secrets: inherit

    deploy-api:
        needs: deploy-az-resources
        if: always() && !contains(needs.*.result, 'failure')
        runs-on: ubuntu-latest
        steps:
          - run: echo ${{ github.job }}
          - name: run yaml
            uses: LoxXo/resume_challenge/.github/workflows/api_deployment.yml@main
            

    deploy-swa-webpage:
        needs: deploy-az-resources
        if: always() && !contains(needs.*.result, 'failure')
        uses: LoxXo/resume_challenge/.github/workflows/azure-static-web-apps-deploy.yml@main
        secrets: inherit
    
    cypress-test:
        needs: [deploy-api, deploy-swa-webpage]
        if: always()
        uses: ./.github/workflows/test_cypress.yml

    always-and-no-failures:
        needs: [deploy-az-resources]
        if: always() && !contains(needs.*.result, 'failure')
        runs-on: ubuntu-latest
        steps:
          - run: echo ${{ github.job }}
