name: Deploy Resume Challenge to Azure
on: 
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
        YOLO:
            default: true
            type: boolean
jobs:
    deploy-az-resources:
        uses: ./.github/workflows/bicep_deployment.yml
        secrets: inherit

    deploy-api:
        needs: deploy-az-resources
        if: always() && needs.deploy-az-resources.result == 'success'
        uses: ./.github/workflows/api_deployment.yml
        secrets: inherit

    deploy-swa-webpage:
        needs: deploy-az-resources
        if: ${{ !failure() && !cancelled() }}
        uses: ./.github/workflows/azure-static-web-apps-deploy.yml
        secrets: inherit
    
    cypress-test:
        needs: [deploy-api, deploy-swa-webpage]
        if: ${{ !failure() && !cancelled() }}
        uses: ./.github/workflows/test_cypress.yml
