name: Cypress E2E Tests for API and Webpage

on:
  # workflow_call:
  workflow_dispatch:
  workflow_run:
    workflows: [Azure Static Web Apps Webpage CI/CD]
    types:
      - completed

env:
  STATIC_WEB_APP_NAME: 'web-resume-00'   # set this to the name of your static web app on Azure
  RESOURCE_GROUP_NAME: 'rg-resume-00'   # set this to the name of your resource group on Azure

jobs:
  # outputs can only be passed inside one job, as we can not use reusable workflows (they're bugged for over a year now)
  # login into azure -> return defaultHostname with az CLI
  get-default-hostname:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    outputs:
      default-hostname: ${{ steps.get-data.outputs.url }}
    steps:
      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get default hostname via Azure CLI
        id: get-data
        run: |
          hostname=$(az staticwebapp show -n '${{ env.STATIC_WEB_APP_NAME }}' -g '${{ env.RESOURCE_GROUP_NAME }}' --query 'defaultHostname' -o tsv)
          echo 'url=$hostname' >> '$GITHUB_OUTPUT'

      - name: test get-data
        run: echo ${{ steps.get-data.outputs.url }}

  cypress-run:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    needs: get-default-hostname
    steps:
      # - name: Sleep for 2 minutes           
      #   uses: jakejarvis/wait-action@v0.1.1
      #   with:
      #     time: '2m'
      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./tests
          build: npm install --verbose
          runTests: false
          
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env: 
          url: ${{ needs.get-default-hostname.outputs.default-hostname }}
        with:
          working-directory: ./tests
          spec: 'cypress/e2e/resume-page-live.cy.js'
          #start: npx cypress run
          command: npx cypress run --env url='${{ env.url }}'
          browser: chrome
